name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Start MySQL container
      run: docker compose up -d

    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL..."
        for i in {1..15}; do
          docker exec mysql_test_container mysqladmin ping -h localhost -ptest_password && break
          echo "Retry $i..."
          sleep 4
        done

    - name: Run tests with coverage
      run: |
        export RUN_DB_TESTS=1
        pytest --cov=src --maxfail=2 --disable-warnings -v tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
